### ISSUE TITLE
ImportError: No module named bng_to_latlon

### ISSUE THREAD

**Issue by Harry-Rogers** [IanHopkinson/defra-lidar-viewer#6]
Hi when I try to run the code using the example I get this import error.

I have used pip install -r requirements.txt and it says I have all of the requirements. Are there other packages I need to use this?

**Comment by IanHopkinson** [comment]
Apologies for the delay - I don't keep an eye on this repo.

It looks like the import is specified wrongly in requirements.txt, it should be
https://pypi.org/project/bng-latlon/
Which needs:
pip install bng_latlon
rather than:
pip install bng-latlon
which is what the requirements.txt implies.
